INSERT INTO ESTUDANTE (CURSO,EMAIL,MATRICULA,NOME,TELEFONE) VALUES ('Engenharia da Computação','xawoy@tms.com.br','123456','Xawoy','7777');
INSERT INTO ESTUDANTE (CURSO,EMAIL,MATRICULA,NOME,TELEFONE) VALUES ('Ciência da Computação','furae@tms.com.br','678912','Furae','7778');
INSERT INTO ESTUDANTE (CURSO,EMAIL,MATRICULA,NOME,TELEFONE) VALUES ('Engenharia da Computação','fupuy@tms.com.br','321654','Fupuy','7779');
INSERT INTO ESTUDANTE (CURSO,EMAIL,MATRICULA,NOME,TELEFONE) VALUES ('Análise de Dados','kuer@tms.com.br','654987','Kuer','7780');
INSERT INTO ESTUDANTE (CURSO,EMAIL,MATRICULA,NOME,TELEFONE) VALUES ('Ciência da Computação','blias@tms.com.br','666131','Blias','7781');